# This file is used by logchange tool to generate CHANGELOG.md 🌳 🪓 => 🪵
# Visit https://github.com/logchange/logchange and leave a star 🌟
# More info about configuration you can find https://github.com/logchange/logchange#yaml-format ⬅️⬅ ️
title: Fixed deployed to maven central repository.
authors:
  - name: Peter Zmilczak
    nick: marwin1991
    url: https://github.com/marwin1991
type: fixed # [added/changed/deprecated/removed/fixed/security/dependency_update/other]
